[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "wordpiece_rs"
version = "0.1.0"
description = "A fast WordPiece tokenizer implementation in Rust"
requires-python = ">=3.7"